# Generated by Django 5.2.12 on 2026-05-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='사용자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 누른 시간')),
            ],
        ),
    ]
